' #Resource Icon, 1, "time_delete.ico"

%VERSION_MAJOR = 1
%VERSION_MINOR = 2
%VERSION_REVISION = 1

#Resource VersionInfo
#Resource FileVersion %VERSION_MAJOR, %VERSION_MINOR, %VERSION_REVISION, 0
#Resource ProductVersion %VERSION_MAJOR, %VERSION_MINOR, %VERSION_REVISION, 0

#Resource StringInfo "0407", "04B0"

#Resource Version$ "CompanyName",      "BasicAware"
#Resource Version$ "FileDescription",  "Numbers/Sorting/Format helpers"
#Resource Version$ "LegalCopyright",   "Copyright 2016-2020 BasicAware"
#Resource Version$ "OriginalFilename", "baNumbers.dll"
#Resource Version$ "ProductName",      "baNumbers"
#Resource Version$ "ProductVersion",   "1.2.1.0"
#Resource Version$ "FileVersion",      "1.2.1.0"
#Resource Version$ "Comments",         "Written by Knuth Konrad"

$COMPANY_NAME = "BasicAware"
